### ISSUE TITLE
force GC after benchmarking

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-minibench#2]
Since this already uses `hrtime`, limiting it to Node, perhaps it's worth forcing the GC after benching?

https://simonmcmanus.wordpress.com/2013/01/03/forcing-garbage-collection-with-node-js-and-v8/

This would stop garbage generated during one run of `bench` from "leaking" into the performance of the next.

**Comment by paf31** [comment]
Sounds like a good idea, but is there no way to do it without requiring the `--expose-gc` flag?

**Comment by paf31** [comment]
I guess we could just do something like `global.gc && global.gc();` and then the user can turn that flag on if they need forced GCs.

Let's add it!

**Comment by matthewleon** [comment]
I've given it some thought and realized it makes sense to issue a GC _before_ benching as well, but before timing starts. It probably makes sense to then incorporate the concluding forced GC in the time statistic.

**Comment by paf31** [comment]
I'd be fine with either - perhaps we should offer a sum type of modes?

**Comment by safareli** [comment]
What about login a warning if `global.gc` is undefined?

**Comment by JordanMartinez** [comment]
This was implemented in #3. I opened #21 to track the other doc concerns.
