### ISSUE TITLE
Add benchCompare

### ISSUE THREAD

**Issue by cprussin** [purescript/purescript-minibench#7]
I have a use case where I need to compare benchmarks from two different implementations of the same function (basically I'm comparing an express.js implementation vs an implementation in a purescript lib I'm working on).  However, I'm seeing odd behavior.  Say the two implementations are A and B.  Then the average time for implementation A is considerably higher when I test it before testing B than when it's the other way around.

My guess is that likely, this is because of v8 artifacts like garbage collection, allocations, etc. that are impacting whichever implementation runs first and causing it's timing to be slower.

I think what would be more accurate is to add a `benchCompare` function to `purescript-minibench`, that would take an array of tests and bench them all, interleaving runs so that each implementation is run once before starting the second run, etc.  That way, any artifacts in v8 will be more likely to have a consistent effect on all the implementations being compared.  @paf31 I wanted to know your thoughts before I put in any work on this one, but I'm happy to do the implementation and submit a PR if you're open to it.

**Comment by paf31** [comment]
Have you tried this with the latest GC changes?

**Comment by cprussin** [comment]
Oh interesting, I saw that but didn't realize you got it merged.  Let me give it a try and report back.  Thanks!

**Comment by cprussin** [comment]
Just FYI, I had to put this on the backburner a bit and still haven't been able to play with it (I need this for a side project and, as life goes, I haven't had much side project time in a while), but I haven't forgotten about it!!!  Whenever I get some time, I'll revisit and follow up.  Thanks.

**Comment by cprussin** [comment]
Going to close this since I haven't had time to work on purescript projects in a while.  I'll reopen later when I do get time to revisit if this is still an issue.
